<h2 style="align:center">DL : Simple NN training for Bonus prediction</h2>

For employee's bonus dataset, implement Neural Network in PyTorch to find optimal values of weights that decides the bonus amount.

Load the dataset

In [56]:
import pandas as pd
from matplotlib import pyplot as plt

# Step 1: Read the dataset from the CSV file
df = pd.read_csv('bonus.csv')
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    1                   3    116
1     EMP_002            4                    8                  10    136
2     EMP_003            8                    4                   5    150
3     EMP_004            5                    4                   7    118
4     EMP_005            7                    5                   6    146

In [57]:
df.shape

(1000, 5)

In [58]:
from sklearn.model_selection import train_test_split

# separate features and target
X = df[['performance', 'years_of_experience', 'projects_completed']].values
y = df[['bonus']].values  # double square brackets to get 2D array

# split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


Train a Neural network

In [59]:
import torch
import torch.nn as nn
import torch.optim as optimizer

In [60]:
X_train.shape

(800, 3)

In [61]:
X_test.shape

(200, 3)

In [62]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [63]:
class BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(3, 1),  # 3 input features -> 1 output neuron
        )

    def forward(self, x):
        return self.network(x)


In [64]:
model = BonusPredictor()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.005)

In [65]:
# Training loop
epochs = 5000
for epoch in range(epochs):
    # Forward pass: Compute predicted bonus by passing X_train
    predictions = model(X_train_tensor)
    loss = criterion(predictions, y_train_tensor)

    # Backward pass: Compute gradients
    optimizer.zero_grad()
    loss.backward()

    # Update parameters
    optimizer.step()

    # Print loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.2f}")

Epoch [100/5000], Loss: 21.97
Epoch [200/5000], Loss: 19.25
Epoch [300/5000], Loss: 16.91
Epoch [400/5000], Loss: 14.88
Epoch [500/5000], Loss: 13.10
Epoch [600/5000], Loss: 11.53
Epoch [700/5000], Loss: 10.15
Epoch [800/5000], Loss: 8.94
Epoch [900/5000], Loss: 7.87
Epoch [1000/5000], Loss: 6.93
Epoch [1100/5000], Loss: 6.10
Epoch [1200/5000], Loss: 5.37
Epoch [1300/5000], Loss: 4.73
Epoch [1400/5000], Loss: 4.16
Epoch [1500/5000], Loss: 3.67
Epoch [1600/5000], Loss: 3.23
Epoch [1700/5000], Loss: 2.84
Epoch [1800/5000], Loss: 2.50
Epoch [1900/5000], Loss: 2.20
Epoch [2000/5000], Loss: 1.94
Epoch [2100/5000], Loss: 1.71
Epoch [2200/5000], Loss: 1.50
Epoch [2300/5000], Loss: 1.32
Epoch [2400/5000], Loss: 1.17
Epoch [2500/5000], Loss: 1.03
Epoch [2600/5000], Loss: 0.90
Epoch [2700/5000], Loss: 0.80
Epoch [2800/5000], Loss: 0.70
Epoch [2900/5000], Loss: 0.62
Epoch [3000/5000], Loss: 0.54
Epoch [3100/5000], Loss: 0.48
Epoch [3200/5000], Loss: 0.42
Epoch [3300/5000], Loss: 0.37
Epoch [3400/

In [66]:
# Switch to evaluation mode (important for models with dropout/batch norm layers)
model.eval()

# Disable gradient calculations for evaluation to save memory
with torch.no_grad():
    test_predictions = model(X_test_tensor)
    test_loss = criterion(test_predictions, y_test_tensor)

print(f"Test Loss: {test_loss.item():.4f}")

Test Loss: 0.0427


In [67]:
X_test_tensor[:3]

tensor([[ 8.,  9., 10.],
        [ 9.,  2.,  5.],
        [ 3.,  7.,  8.]])

In [68]:
test_predictions[:3]

tensor([[189.9574],
        [150.1579],
        [113.7272]])

In [69]:
y_test_tensor[:3]

tensor([[190.],
        [150.],
        [114.]])

In [70]:
for name, value in model.named_parameters():
    print(f"Name: {name}, Value: {value}")

Name: network.0.weight, Value: Parameter containing:
tensor([[12.0338,  5.8404,  2.1901]], requires_grad=True)
Name: network.0.bias, Value: Parameter containing:
tensor([19.2222], requires_grad=True)
